using System;

public enum EVENT_TYPE
{
	GAME_STARTED,
	ZOMBIE_KILLED,
	ZOMBIE_IN_ATTACK_ZONE,
	ZOMBIE_LEAVE_ATTACK_ZONE,
	BOSS_LOOSE,
	BOSS_WIN,
	EXP_GROW,
	EXP_FALL,
	WAVE_STARTED,
	LEVEL_READY_UP,
	LEVEL_UP,
	UNLOAD_LEVEL,
	LEVEL_LOADED,
	LEVEL_UP_BTN_CLICKED,
	CHOOSE_LOCATION_CLICKED,
	CHARACTERS_CHANGED,
	LOCATION_CHANGED,
	LOADING_FINISHED
}
