// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var baseAscendRewardDesign = BaseAscendRewardDesign.FromJson(jsonString);

namespace QuickType.Ascend
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BaseAscendRewardDesign
    {
        [JsonProperty("BaseAscendReward", Required = Required.Always)]
        public List<BaseAscendReward> BaseAscendReward { get; set; }
    }

    public partial class BaseAscendReward
    {
        [JsonProperty("StartLevel", Required = Required.Always)]
        public long StartLevel { get; set; }

        [JsonProperty("BaseTokenReturn", Required = Required.Always)]
        public long BaseTokenReturn { get; set; }

        [JsonProperty("StepTokenReturn", Required = Required.Always)]
        public long StepTokenReturn { get; set; }

        [JsonProperty("BasePill", Required = Required.Always)]
        public long BasePill { get; set; }

        [JsonProperty("StepPill", Required = Required.Always)]
        public long StepPill { get; set; }
    }

    public partial class BaseAscendRewardDesign
    {
        public static BaseAscendRewardDesign FromJson(string json) => JsonConvert.DeserializeObject<BaseAscendRewardDesign>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this BaseAscendRewardDesign self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
