// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var campaignRewardDesign = CampaignRewardDesign.FromJson(jsonString);

namespace QuickType.Config
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GeneralConfig
    {
        [JsonProperty("GeneralConfig", Required = Required.Always)]
        public List<ConfigDesign> Config { get; set; }
    }

    public partial class ConfigDesign
    {
        [JsonProperty("KeyID", Required = Required.Always)]
        public string KeyId { get; set; }

        [JsonProperty("Value", Required = Required.Always)]
        public long Value { get; set; }
    }

    public partial class GeneralConfig
    {
        public static GeneralConfig FromJson(string json) => JsonConvert.DeserializeObject<GeneralConfig>(json, QuickType.Config.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this GeneralConfig self) => JsonConvert.SerializeObject(self, QuickType.Config.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
