// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var allWeaponDes = AllWeaponDes.FromJson(jsonString);

namespace QuickType.HeroAngel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ManualHeroDesign
    {
        [JsonProperty("ManualHeroDesign", Required = Required.Always)]
        public List<ManualHeroDesignElement> ListManualHeroDesign { get; set; }
    }

    public partial class ManualHeroDesignElement
    {
        [JsonProperty("HeroID", Required = Required.Always)]
        public string HeroId { get; set; }

        [JsonProperty("Rarity", Required = Required.Always)]
        public long Rarity { get; set; }

        [JsonProperty("BonusDmgPerLevel", Required = Required.Always)]
        public float BonusDmgPerLevel { get; set; }
    }

    public partial class ManualHeroDesign
    {
        public static ManualHeroDesign FromJson(string json) => JsonConvert.DeserializeObject<ManualHeroDesign>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ManualHeroDesign self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
