// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var mapObstacleRatioDesign = MapObstacleRatioDesign.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class MapObstacleRatioDesign
    {
        [JsonProperty("MapObstacleRatioDesign")]
        public List<MapObstacleRatioDesignElement> MapObstacleRatioDesignElements { get; set; }
    }

    public partial class MapObstacleRatioDesignElement
    {
        [JsonProperty("MAP_ObstacleID")]
        public string MapObstacleId { get; set; }

        [JsonProperty("Level")]
        public long Level { get; set; }
    }

    public partial class MapObstacleRatioDesign
    {
        public static MapObstacleRatioDesign FromJson(string json) => JsonConvert.DeserializeObject<MapObstacleRatioDesign>(json, QuickType.Converter.Settings);
    }

    public static partial class Serialize
    {
        public static string ToJson(this MapObstacleRatioDesign self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }
}
