// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var missionDesign = MissionDesign.FromJson(jsonString);

namespace QuickType
{
 
    
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    
    public enum MissionType
    {
        KILL_ZOMBIE,
        FINISH_LEVEL,
        UPGRADE_HERO,
        USE_ULTIMATE,
        USE_ADDON,
        OPEN_CHEST,
        UPGRADE_EQUIPMENT,
        LOGIN,
        CLAIM_OFFLINE_REWARD,
        FUSION_EQUIP,
        WATCH_VIDEO_OPEN_CHEST,
        GET_FREE_RESOURCE
    };
    

    public partial class MissionDesign
    {
        [JsonProperty("MissionDesign")]
        public List<MissionDesignElement> MissionDesignElements { get; set; }
    }

    public partial class MissionDesignElement
    {
        [JsonProperty("ID", Required = Required.Always)]
        public string Id { get; set; }

        [JsonProperty("Type", Required = Required.Always)]
        public MissionType Type { get; set; }

        [JsonProperty("Total", Required = Required.Always)]
        public long Total { get; set; }
        
        [JsonProperty("Description", Required = Required.Always)]
        public string Description { get; set; }

        [JsonProperty("Extend")]
        public string Extend { get; set; }
        
        [JsonProperty("Reward", Required = Required.Always)]
        public List<Reward> Rewards { get; set; }
    }


    public partial class MissionDesign
    {
        public static MissionDesign FromJson(string json) => JsonConvert.DeserializeObject<MissionDesign>(json, QuickType.Converter.Settings);
    }
}