// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var missionDurationDesign = MissionDurationDesign.FromJson(jsonString);

using UnityEngine;

namespace QuickType
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class MissionDurationDesign
    {
        [JsonProperty("MissionDurationDesign", Required = Required.Always)]
        public List<MissionDurationDesignElement> MissionDurationDesignElements{ get; set; }
    }

    public partial class MissionDurationDesignElement
    {
        [JsonProperty("ID", Required = Required.Always)]
        public string Id { get; set; }

        [JsonProperty("Duration", Required = Required.Always)]
        public long Duration { get; set; }

        [JsonProperty("Missions", Required = Required.Always)]
        public string Missions { get; set; }
        
        [JsonProperty("Level", Required = Required.Always)]
        public int Level{ get; set; }

        [JsonProperty("Reward", Required = Required.Always)]
        public List<Reward> Reward { get; set; }
    }

    public partial class MissionDurationDesignElement
    {
        public List<MissionDesignElement> GetMissionsDesign()
        {
            List<MissionDesignElement> result = new List<MissionDesignElement>();
            string[] ids = Missions.Split(',');
            foreach (var id in ids)
            {
                result.Add(DesignHelper.GetMissionDesign(id));
            }

            return result;
        }
    }

    public partial class MissionDurationDesign
    {
        public static MissionDurationDesign FromJson(string json) =>
            JsonConvert.DeserializeObject<MissionDurationDesign>(json, QuickType.Converter.Settings);
    }
}