// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var zombieRatioDesign = ZombieRatioDesign.FromJson(jsonString);

namespace QuickType.ZombieRatio
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ZombieRatioDesign
    {
        [JsonProperty("ZombieRatioDesign", Required = Required.Always)]
        public List<ZombieRatioDesignElement> ZombieRatioDesignZombieRatioDesign { get; set; }
    }

    public partial class ZombieRatioDesignElement
    {
        [JsonProperty("RatioID", Required = Required.Always)]
        public string RatioId { get; set; }

        [JsonProperty("Ratio", Required = Required.Always)]
        public List<Ratio> Ratio { get; set; }
    }

    public partial class Ratio
    {
        [JsonProperty("ZombieID", Required = Required.Always)]
        public string ZombieId { get; set; }

        [JsonProperty("Percent", Required = Required.Always)]
        public long Percent { get; set; }

        [JsonProperty("Priority", Required = Required.Always)]
        public int Priority { get; set; }
    }

    public partial class ZombieRatioDesign
    {
        public static ZombieRatioDesign FromJson(string json) => JsonConvert.DeserializeObject<ZombieRatioDesign>(json, QuickType.ZombieRatio.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ZombieRatioDesign self) => JsonConvert.SerializeObject(self, QuickType.ZombieRatio.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
